### ISSUE TITLE
render options issues

### ISSUE THREAD

**Issue by lwnhp** [straydogstudio/axlsx_rails#47]
the 'render' action is working, however I've encountered the following issues:
1. while specifying the template to render, I had to explicit name the .xlsx.axlsx file extension, otherwise I got an error "template not found". In the instructions the file extension is not named?

2. I can't get the option  > disposition: "inline" < to work; using this option the file is still downloaded?

my action look like this now:

def report
    render xlsx: "scanreport", template: "scans/report.xlsx.axlsx", disposition: 'inline'
  end

thnx in advance!

**Comment by straydogstudio** [comment]
@lwnhp Let me know your versions for Rails, axlsx, axlsx_rails. I will try to take a look at the extensions. 

Regarding the inline header, can you use Chrome debugging tools or the like to confirm the header is present on the returned file? It should show up on the network tab. In my experience disposition is a suggestion to the browser: browsers will sometimes do otherwise.

**Comment by lwnhp** [comment]
I’m using Cloud9:

rails 4.4
axlsx 2.0.1
xlsx_rails 0.4.0

i’ll look into the header and let you know.

grt. Berry Straver

**Comment by straydogstudio** [comment]
@lwnhp Did you ever solve this?

**Comment by lwnhp** [comment]
No, not realy. In the end axlsx turned out not to be the right solution for my reports. There's a lot of formatted text in my reports, and unfortunately axlsx is not capable of handling rich text in cells. So I switched to [wicked_pdf]http://mileszs.com/blog/2009/06/17/wicked-pdf-plugin.html), giving me rich text plus inline disposition. thnx, cheers BS
