### ISSUE TITLE
Worksheet names can't exceed 31 characters

### ISSUE THREAD

**Issue by ppelgrims** [straydogstudio/axlsx_rails#68]
Worksheet names can't exceed 31 characters or excel generation will fail. I'm not sure if automatically truncating these would be the right solution, but I do reckon this is the gem's responsibility. Thoughts?

**Comment by straydogstudio** [comment]
That's actually inside [Axlsx](https://github.com/randym/axlsx/blob/master/lib/axlsx/workbook/worksheet/worksheet.rb#L703), not axlsx_rails.

Given that @randym wrote with the specification in mind, I'm pretty sure that's a limitation of XLSX spreadsheets. Certainly it is for XLS. I also expect it was a conscious decision to alert someone that their name was too long, rather than to silently truncate. But you can certainly make the suggestion through the axlsx gem. 

Reopen if you can show something axlsx_rails should do.
